ui: mocha-bdd
server: ./test/support/server.js
browsers:
  - name: firefox
    version: 44..latest
    platform: Mac 10.10
  - name: opera
    version: latest
    platform: Mac 10.10
  - name: chrome
    version: 45..latest
  - name: safari
    version: 7..latest
  - name: ie
    version: 10..latest
  - name: android
    version: '4.4..latest'
  - name: iphone
    version: '7.1..latest'
  - name: MicrosoftEdge
    platform: Windows 10
    version: '20.10240..latest'
